"""Adicionar campo openpix_app_id em User

Revision ID: 2454e19b8bbd
Revises: a202c5abb739
Create Date: 2025-09-08 22:25:12.765797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2454e19b8bbd'
down_revision: Union[str, Sequence[str], None] = 'a202c5abb739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sale_items_product_id_fkey'), 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'products', ['product_id'], ['id'])
    op.add_column('users', sa.Column('openpix_app_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'openpix_app_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.create_foreign_key(op.f('sale_items_product_id_fkey'), 'sale_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
