"""Adicionar ON DELETE CASCADE na chave estrangeira de sale_items

Revision ID: 2485d36aba56
Revises: 5fe78a0272e6
Create Date: 2025-09-08 18:50:04.981040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2485d36aba56'
down_revision: Union[str, Sequence[str], None] = '5fe78a0272e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint('sale_items_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'sale_items_product_id_fkey',
            'products',
            ['product_id'],
            ['id'],
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint('sale_items_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'sale_items_product_id_fkey',
            'products',
            ['product_id'],
            ['id']
        )
